### ISSUE TITLE
Support use of session token after authenticating using username / password

### ISSUE THREAD

**Issue by nbateshaus** [Datatamer/tamr-client#305]
# 🙋 feature request

Right now, there's no easy way to graduate from UsernamePasswordAuth to TokenAuth. The downside of just using UsernamePasswordAuth is twofold:
1. It creates a new session with every request, significantly increasing the load on the auth service
2. It re-sends credentials with every request, significantly increasing the exposure of the credentials.

The downside of TokenAuth is:
1. There is no way to get a session token, other than raw API calls.

Ideally, when creating a client with UsernamePasswordAuth, it would capture the returned session token and use the cached token to authenticate requests until the session times out.

## 🤔 Expected Behavior

```
tamr = api.Client(UsernamePasswordAuth(user, password), host=host)`
projects = client.projects()
datasets = client.datasets()
```
In the above example, projects and datasets should be fetched using the same session

## 😯 Current Behavior

In the above example, projects and datasets are fetched using different sessions.

## 💁 Possible Solution

Create an authenticator that takes the protocol, host, port, username, password of the auth service to fetch a session token, then behaves like token auth as long as the session token is valid.
Ideally, we'd then deprecate then remove `UsernamePasswordAuth` to encourage migration to the better pattern.

## 🔦 Context

Just try'n'a get stuff done, and I'm accidentally hammering on the auth service.

## 💻 Examples

See above.

**Comment by pcattori** [comment]
I talked to @mfbanner-tamr a couple weeks ago about this. `TokenAuth` is a misnomer; it is just accepting the `base64`-encoded version of the user credentials rather than the plaintext (like how `UsernamePasswordAuth` works).

We are already using [`requests.Session`](https://2.python-requests.org/en/master/user/advanced/#session-objects) under-the-hood (see #79 ), but more work is necessary to avoid resending auth header. E.g. the Tamr UI stores the *actual* auth token in a cookie. We could do that, but we'd have to [manually store that information in the session cookies](https://2.python-requests.org/en/master/user/advanced/#session-objects). We'd also need to implement logic for refreshing auth from expired tokens.

Not sure how near-term this would be but @mfbanner-tamr was planning some changes to the Auth service that would impact this, so might be worth holding off on adding this feature until the dust settles around the Auth service depending on timing.

**Comment by pcattori** [comment]
Let's just copy how the UI does this:
- hit the Auth service
- store the auth token in the session cookie

**Comment by pcattori** [comment]
See https://stackoverflow.com/a/51904567/1490091
