### ISSUE TITLE
Better error reporting for 500 errors

### ISSUE THREAD

**Issue by clint-richardson** [Datatamer/tamr-client#321]
# 🙋 feature request

Currently a 500 error throws a hard-to-interpret error message:

```
return cls(client, data, api_path)
File "/usr/local/lib/python3.7/site-packages/tamr_unify_client/models/base_resource.py", line 17, in __init__
    self.api_path = alias or data["relativeId"]
TypeError: string indices must be integers
```

In my case it turned out to be the gcp instance had run out of space. If there is a request that *should* work, can you advise checking the logs/health of the instance?

## 😯 Current Behavior

Indecipherable error message

## 💁 Possible Solution

Tell user to check the logs/health of the instance

**Comment by pcattori** [comment]
Should be fixed by #315 

Specifically, enabling logging will as described in [User Guide > Logging](https://tamr-client.readthedocs.io/en/0.12.1/user-guide/logging.html) will give you access to the response body for a response with an HTTP error code.

In the future:
- If responses contain semantically contain error descriptions in their body but do not syntactically contain an error in their HTTP status code, this should be fixed upstream in the API.
- If any specific error is not captured by logging, one can file a Github issue requesting to fix handling for that specific error.

We can reopen this issue if anyone observes systematic mishandling of generic errors in this codebase.
