### ISSUE TITLE
Address review comments for the new tamr-client continuous mastering tutorial

### ISSUE THREAD

**Issue by lamagnifica** [Datatamer/tamr-client#470]
https://github.com/Datatamer/tamr-client/pull/469#pullrequestreview-518076196

@pcattori @skalish FYI

**Comment by skalish** [comment]
@lamagnifica I've created a follow-up PR addressing some of these requested changes here #471.  If there are more changes to be made, I'm happy to make them.  I would also say (though @pcattori can disagree here) that there is no pressure to rush this, since it isn't blocking anything from being merged.

In fact, in the future this is maybe the best mode of operation.  We can merge tutorials and other field-written documentation after a brief review and iterate with more detailed feedback and revision with a polishing PR that can stay open as long as is necessary.
